### PR TITLE
Church circles health and visual update

### PR DESCRIPTION
**Pull request by incraigulous**
This PR adds new church health icons to the genmapper church circles nodes.

#### Features: 

- New church circle styles as inspired by https://github.com/DiscipleTools/disciple-tools-theme/pull/1481. 
- Church health icons and metrics added to church circles as inspired by https://github.com/DiscipleTools/disciple-tools-genmapper/blob/master/includes/charts/church-circles/genmapper-node-example-church-circles.png
- Admin interface for adding custom icons. This can later be expanded to choosing custom health statistics and icon placement once additional metrics are available.
- The new church health metrics that show above the church health circles are also added to the group page. Those metrics are dynamically updated as contacts are updated, but can also be overwritten manually by the user. 
- Unit tests have also been added.

genmapper-1 1

Screen Shot 2021-10-22 at 10 26 42 AM

genmapper-4

### CODE REVIEW

**Comment by corsacca** [comment]
in includes/functions.php `get_option("dt_genmapper_show_health_metrics")` by default is false. 
But the box is checked in the admin settings:
image

**Comment by corsacca** [comment]
Any thoughts on making this section use up less space?
Or maybe the extra 3 fields are not shown by default?
image

**Comment by corsacca** [comment]
@incraigulous  we are also adding a way to upload replacement icons in this PR: https://github.com/DiscipleTools/disciple-tools-theme/pull/1515

**Comment by incraigulous** [comment]
@corsacca 

**Re: fields taking less space:** 
That's a great idea! On it. 

**Re: replacement icons PR**
I'm glad this is underway. I'm not quite sure how I could hook into this since the icons in the PR are tied to fields. Any action you would like me to take based on that PR?

**Comment by corsacca** [comment]
@incraigulous are the icons in the group circle not linked to the `health_metrics` field?

**Comment by incraigulous** [comment]
@corsacca They aren't, they only show up on the gen map.

**Comment by incraigulous** [comment]
It's now pulling the icons from the group fields. The leader count icon looks a little out-of-place. It is part of the theme, not the plugin.

Screen Shot 2021-11-12 at 4 47 30 PM

**Comment by incraigulous** [comment]
@corsacca I collapsed the metrics fields by default.
Screen Shot 2021-11-15 at 6 11 14 PM
Screen Shot 2021-11-15 at 6 11 21 PM
Screen Shot 2021-11-15 at 6 11 29 PM

**Comment by incraigulous** [comment]
Screen Shot 2021-11-18 at 12 24 37 PM

Added a new baptized in group icon and believers icon.

**Comment by incraigulous** [comment]
@corsacca I believe is ready to be merged in!

**Comment by incraigulous** [comment]
@corsacca I believe I've made the requested changes!

**Comment by corsacca** [comment]
I'm still getting this behavior:
not_saving_2

To reproduce, delete the `dt_genmapper_*` values from the wp_options table
If you load the settings page for the first time, unchecking `dt_genmapper_collapse_metrics` will not save "false" to the option table because the `dt_genmapper_collapse_metrics` key is not created yet. So it will default back to `true`.
Once `true` has been saved, then setting it to false will work.

**Comment by incraigulous** [comment]
@corsacca this is fixed!

**Comment by corsacca** [comment]
Thanks @incraigulous !

**Pull request merged**
